### ISSUE TITLE
Broken styling

### ISSUE THREAD

**Issue by mudrd8mz** [academic-moodle-cooperation/moodle-blocks_semester_sortierung#1]
I am experiencing some unexpected border styling issues with recent version of the block at Moodle 2.8. See the attached screenshot for illustration.

![semsort](https://cloud.githubusercontent.com/assets/85831/8427274/68b7814c-1f16-11e5-9cf3-3d94ca8fb22a.png)

**Comment by kaspot** [comment]
forwarded it to our developers. Will try to fix it asap.

**Comment by kaspot** [comment]
We've uploaded the newest version for 2.8 and this issue should be fixed.
