### ISSUE TITLE
Languages other than English need not be included in the ZIP file

### ISSUE THREAD

**Issue by germanvaleroelizondo** [academic-moodle-cooperation/moodle-blocks_semester_sortierung#2]
Hi,
I just translated the semester overview plugin into mexican spanish at AMOS (https://lang.moodle.org/).

According to AMOS https://lang.moodle.org/mod/forum/discuss.php?d=2485 , nowadays it is not necessary nor convenient to include foreign (non-English) language strings inside plugin files for download.

When a user installs this plugin from the Moodle web interface there is an info warning about 'Langfile found', but it installs correctly. I think that if you remove the German  language file inside the 'lang/de' folder, this warning message would disappear.

I submitted the german language strings found inside the semester overview block ZIP file to the German language pack maintainer at AMOS (Ralf Krause at https://lang.moodle.org/user/view.php?id=32&course=2), so that these strings can be handled as all other translations.

Thanks for another nice plugin.

**Comment by germanvaleroelizondo** [comment]
Hi,
The German language strings for this plugin have been accepted in AMOS by the German language pack maintainer :)

**Comment by kaspot** [comment]
Thanks a lot.
