### ISSUE TITLE
Missing February?

### ISSUE THREAD

**Issue by aruethe2** [academic-moodle-cooperation/moodle-blocks_semester_sortierung#5]
When setting the Months of the winter semester, February is not included as a choice.  Should February be included?

![february](https://cloud.githubusercontent.com/assets/1678565/18093149/e9365902-6e9c-11e6-94cb-7d14bfa90a31.png)

**Comment by kaspot** [comment]
Hi, 
I'm not really sure what exactly happened, but it is strange. I just checked our current 3.1 version and everything seems to be alright. 
May I ask you to give us the moodle version you are running and also the version of the block (from version.php). 
<img width="885" alt="screen shot 2016-08-31 at 07 16 55" src="https://cloud.githubusercontent.com/assets/1519714/18116814/009d3936-6f4b-11e6-91e3-aa7168479dcd.png">

**Comment by lucaboesch** [comment]
Not sure if the both of you noticed: In the first screenshot there's December twice.

**Comment by kaspot** [comment]
Yes, thanks for pointing that out. I noticed it — still some more details would be great. Next step would be to take a look in the db in config_plugins table ;-)
Can't really imagine how this could have happened ;-)

**Comment by aruethe2** [comment]
We are running Moodle Moodle 3.1.1+ (Build: 20160728) and the plugin version.php says 
$plugin->version   = 2016072800;
$plugin->release   = "v3.1.0";       

I am not an expert PHP programmer, but it looks to me like line 43 in settings.php is assuming that there are 31 days in each month:
`$monthsarray['mon' . (($i + 1) < 10 ? '0' : '') . strval($i + 1)] = strftime('%B', ($i * 3600 * 24 * 31));`

Perhaps something like this would work (idea from http://stackoverflow.com/a/10829455)

``` php
for ($i = 1; $i <= 12; $i++) {  
        $monthsarray['mon' . (($i + 1) < 10 ? '0' : '') . strval($i + 1)] = date('F', mktime(0,0,0,$i, 1, date('Y')));  
        if ($i < 1 || $i > 5) {  
            $selected['mon' . (($i + 1) < 10 ? '0' : '') .  strval($i + 1)] = 1;  
        }  
    }
```

If it helps to explain things, I am in the United States but I cannot explain why that would make a difference.

**Comment by aruethe2** [comment]
Actually, I believe this is a timezone related problem.  If you are working in Austria, you are ahead of UTC.  In the US, I am behind UTC.  At January 1 00:00 UTC, you are actually January 1 01:00, but I am December 31 19:00.  That is why I see December as the first month and you see January as the first month.  

In the next iteration we add 31 days, which makes it February 1 00:00 UTC.  In Vienna, that is February 1 01:00 and I show January 31 19:00.  So the second month is February for you and January for me.

In the next iteration, we add another 31 days which makes it March 3 00:00 UTC.  You see March 3 01:00 and I see March 2 19:00.  So the third month is March for both of us.  

Because we are now always adding 31 days, we are never on the 1st day of the month again, so we are always in sync, except I have an extra month at the end.

**Comment by kaspot** [comment]
Thanks for those details - I will forward this to our developer.

**Comment by kaspot** [comment]
This one should be fixed already. Please check out the newest version and tell us what you think about it. 
Cheers Kat
