### ISSUE TITLE
Problem when trying to move the block with drag & drop in Dashboard

### ISSUE THREAD

**Issue by stemiwe** [academic-moodle-cooperation/moodle-blocks_semester_sortierung#6]
We are using Moodle 3.4.1 with Boost theme, and the block behaves very strange when I try to move it via drag & drop.

What happens is that I cannot "drop" it anywhere, it keeps following the mouse cursor until I click "Stop customising this page" to quit edit mode for the Dashboard.

What's worse is that this affects ALL OTHER blocks as well as soon as I add semester_sortierung to my Dashboard.

This happens to all users in both Chrome and Firefox

Since this bug stops us from using this otherwise great plugin that offers exactly the functionality we want, it would be great if this could be fixed.

**Comment by moniNaydenov** [comment]
Hi,

Thanks a lot for pointing out that bug!
It is now fixed and will be published as soon as it is tested.

Best regards,
Simeon

**Comment by stemiwe** [comment]
this should be closed, as it was fixed
