### ISSUE TITLE
block stops working after upgrading 3.4.2 to 3.4.3

### ISSUE THREAD

**Issue by stemiwe** [academic-moodle-cooperation/moodle-blocks_semester_sortierung#7]
i just upgraded our test site from 3.4.2 to 3.4.3, and the semester_sortierung block stopped working:

**Coding error detected, it must be fixed by a programmer: Request for an unknown renderer block_semester_sortierung, , general**

**Comment by stemiwe** [comment]
it works again after reinstalling the plugin. we had the same issue when upgrading from moodle 3.3 to moodle 3.4.2, also using the latest version of semester_sortierung.

the problem is, since then I added semester_sortierung to our default dashboard, so im very reluctant to uninstall/reinstall it, as that would also require resetting the dashboard for all users to re-add it there.

**Comment by stemiwe** [comment]
interestingly, upgrading our prod site from 3.4.2 to 3.4.3, which the test site is basically just a clone of, worked without reinstalling the plugin

however, on the test site, i had the same behaviour when upgrading 3.4.3 further to 3.5, this time with logging enabled:

Coding error detected, it must be fixed by a programmer: Request for an unknown renderer block_semester_sortierung, , general
Debug info: 
Error code: codingerror
Stack trace:
line 447 of /lib/outputfactories.php: coding_exception thrown
line 2380 of /lib/outputlib.php: call to theme_overridden_renderer_factory->get_renderer()
line 864 of /lib/pagelib.php: call to theme_config->get_renderer()
line 83 of /blocks/semester_sortierung/block_semester_sortierung.php: call to moodle_page->get_renderer()
line 288 of /blocks/moodleblock.class.php: call to block_semester_sortierung->get_content()
line 230 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 1211 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1263 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 590 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
line 95 of /theme/boost/classes/output/core_renderer.php: call to core_renderer->standard_head_html()
line 219 of /lib/mustache/src/Mustache/Context.php: call to theme_boost\output\core_renderer->standard_head_html()
line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
line 31 of /documents/moodledata/localcache/mustache/1527252194/boost/__Mustache_e8d8ae873a984614cbb0bd0c2a191036.php: call to Mustache_Context->findDot()
line 13 of /documents/moodledata/localcache/mustache/1527252194/boost/__Mustache_827ef2e40367ddf01c85283e8cc57ac0.php: call to __Mustache_e8d8ae873a984614cbb0bd0c2a191036->renderInternal()
line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_827ef2e40367ddf01c85283e8cc57ac0->renderInternal()
line 177 of /lib/outputrenderers.php: call to Mustache_Template->render()
line 55 of /theme/boost/layout/columns2.php: call to renderer_base->render_from_template()
line 1272 of /lib/outputrenderers.php: call to include()
line 1202 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 164 of /my/index.php: call to core_renderer->header()

**Comment by stemiwe** [comment]
same problem now on the prod site upgrading 3.4.2 to 3.5.1...

**Comment by goggo24** [comment]
@webers-technikum-wien: did the error also appear on upgrading to 3.6.x ? We just upgraded from different 3.5.x moodle core versions to 3.6.2 with semsort v.3.6.0. and all our amc partners, didn't had any problems. Did it work out this time?

**Comment by stemiwe** [comment]
no, the update to 3.5.1 was the last time we encountered this problem.

since it was so hard to reproduce and happened so inconsistently i don't think there is any hope of finding out what exactly caused it, so i guess it's best to just close the issue.
