### ISSUE TITLE
Notice if archive is not set in config.

### ISSUE THREAD

**Issue by lucaboesch** [academic-moodle-cooperation/moodle-blocks_semester_sortierung#8]
Upon a new install, if the block hasn't been configured, page set to report all warning and notices and accessing as a student, Moodle throws a notice saying

**Notice**:  Undefined property: stdClass::$archive in **blocks/semester_sortierung/block_semester_sortierung.php** on line **186**

Thank you for your enquiry.

**Comment by goggo24** [comment]
Thanks Luca for reporting :) We will have a look and hopefully we can already include the fix in version v.3.6.0. Greetings to switzerland!

**Comment by goggo24** [comment]
included in v.3.6.0 - coming soon!
